version: '3.9'

services:

 db:
  image: postgres:13.2-alpine
  restart: always
  environment:
   POSTGRES_PASSWORD: hasloDoBazy
   POSTGRES_DB: MediaryDB
  volumes:
   - "./data:/var/lib/postgresql/data"
  ports:
   - 5432:5432

 adminer:
  image: adminer
  restart: always
  ports:
   - 2211:8080